#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#


def miniMaxSum(arr):
    # Assumes an array of 5 integers
    arr.sort()
    min_val = 0
    for i in range(4):
        min_val += arr[i]
    max_val = 0
    for i in range(1, 5):
        max_val += arr[i]
    print(f"{min_val} {max_val}")


if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
