#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countApplesAndOranges' function below.
#
# The function accepts following parameters:
#  1. INTEGER s - start of house
#  2. INTEGER t - end of house
#  3. INTEGER a - location of apple tree
#  4. INTEGER b - location of orange tree
#  5. INTEGER_ARRAY apples
#  6. INTEGER_ARRAY oranges
#


def countApplesAndOranges(s, t, a, b, apples, oranges):
    # apple_count = 0
    # orange_count = 0
    house_start = s
    house_end = t
    # for distance in apples:
    #     location = a + distance
    #     on_house = location >= house_start and location <= house_end
    #     if on_house:
    #         apple_count += 1
    # for distance in oranges:
    #     location = b + distance
    #     on_house = location >= house_start and location <= house_end
    #     if on_house:
    #         orange_count += 1
    # print(apple_count)
    # print(orange_count)
    print(count_one(house_start, house_end, a, apples))
    print(count_one(house_start, house_end, b, oranges))


def count_one(house_start, house_end, tree_location, distances):
    count = 0
    for distance in distances:
        location = tree_location + distance
        on_house = location >= house_start and location <= house_end
        if on_house:
            count += 1
    return count


if __name__ == '__main__':
    # first_multiple_input = input().rstrip().split()

    # s = int(first_multiple_input[0])

    # t = int(first_multiple_input[1])

    # second_multiple_input = input().rstrip().split()

    # a = int(second_multiple_input[0])

    # b = int(second_multiple_input[1])

    # third_multiple_input = input().rstrip().split()

    # m = int(third_multiple_input[0])

    # n = int(third_multiple_input[1])

    # apples = list(map(int, input().rstrip().split()))

    # oranges = list(map(int, input().rstrip().split()))

    s = 7
    t = 11
    a = 5
    b = 15
    apples = [-2, 2, 1]
    oranges = [5, -6]
    countApplesAndOranges(s, t, a, b, apples, oranges)
